simplemps/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .self_service_api import getCostPerCartridge, create_proposal_network_device_self_service

from .views import (
    AccessoryViewSet,
    ManagerAlertViewSet,
    PrinterCostAPIView,
    PageCostViewSet,
    ProposalPurchaseItemViewSet,
    ProposalServiceItemViewSet,
    ProposalViewSet,
    TonerViewSet,
    ClientViewSet
)


router = DefaultRouter()
router.register(r'accessories', AccessoryViewSet)
router.register(r'manager-alerts', ManagerAlertViewSet)
router.register(r'page-costs', PageCostViewSet)
router.register(r'proposals', ProposalViewSet)
router.register(r'proposal-purchase-items', ProposalPurchaseItemViewSet)
router.register(r'proposal-service-items', ProposalServiceItemViewSet)
router.register(r'toners', TonerViewSet)
router.register(r'client-info', ClientViewSet)

urlpatterns = [
    path('printer-cost/<int:pk>/', PrinterCostAPIView.as_view()),
    path('self-service-ppc/<int:proposal_id>/<int:printer_id>/', getCostPerCartridge),
    path('self-service/addNetworkDeviceSelfService/<int:proposal_id>/', create_proposal_network_device_self_service),
]

urlpatterns += router.urls

simplemps/mps/urls.py
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView

from . import views
from .controllers import imports, model_update
from .controllers import dca, print_fleet_
from .self_service import get_self_service_landing, get_self_service_equipment, get_self_service_selection, get_self_service_review, get_self_service_selection_landing

app_name = 'mps'

PROPOSAL_URLS = [
    path('createNewProposalSelfService/', model_update.create_proposal_external_source),
    path('updateProposalUserInfoSelfService/', model_update.update_proposal_user_info_self_service),
    path('createNewProposal/', model_update.create_proposal),
    path('selectClient/', RedirectView.as_view(url='/openProposals')),
    path('selectClient/<int:client_id>/edit', model_update.update_client),
    path('selectClient/<int:proposal_id>/', views.select_client),
    path('selectClient/saveProposal/', model_update.update_proposal_client_page),
    path('saveNewClient/', model_update.create_client),
    path('saveProposedCPP/', views.save_proposed_cpp),
    path('details/', RedirectView.as_view(url='/openProposals')),
    path('details/<int:proposal_id>/', views.proposal_details),
    path('getCompanyForExternalSource/', model_update.get_company_info_external_source),
    path('getManagementSettings/<int:assumptions_id>/', views.get_management_settings),
    path('getProposalSettings/<int:proposal_id>/', views.get_proposal_settings),
    path('getProposalItems/<int:proposal_id>/', views.get_proposal_items),
    path('getProposalPurchaseItem/<int:proposal_purchase_item_id>/', views.get_proposal_purchase_item),
    path('details/saveProposal/', model_update.update_proposal_details_page),
    path('pricing/', RedirectView.as_view(url='/openProposals')),
    path('pricing/<int:proposal_id>/update_tco_calculations', model_update.update_tco_calculations),
    path('pricing/<int:proposal_id>/', views.proposal_pricing, name="proposal_pricing"),
    path('TCO/<int:proposal_id>/', views.proposal_tco, name="proposal_tco"),
    path('TCO/<int:proposal_id>/sync', views.proposal_tco_sync, name="proposal_tco_sync"),
    path('getTCO/<int:proposal_id>/', views.proposal_get_tco, name="proposal_get_tco"),
    path('TCO/saveProposalTCO/', model_update.update_proposalTCO),
    path('TCO/<int:proposal_id>/updateTCODevice/', model_update.update_tco_device),
    path('getNetworkDeviceDetails/', views.get_network_device_details),
    path('getNonNetworkDeviceDetails/', views.get_non_network_device_details),
    path('getMakeDetails/', views.get_make_details),
    path('getPrinterDetails/', views.get_printer_details),
    path('getPrinterDetailsByMake/<int:make_id>/', views.get_printer_details_byMake),
    path('getUpdatedProposalServiceItems/<int:proposal_id>/', views.get_proposal_service_items_list),
    path('view/cpp/<int:proposal_id>/', views.view_proposal_cpp, name='view_proposal_cpp'),
    path('view/nc/<int:proposal_id>/', views.view_proposal_nc, name='view_proposal_nc'),
    path('view/blended/<int:proposal_id>/', views.view_proposal_blended, name='view_proposal_blended'),
    path('view/tiered/<int:proposal_id>/', views.view_proposal_tiered, name='view_proposal_tiered'),
    path('view/ppc/<int:proposal_id>/', views.view_proposal_ppc, name='view_proposal_ppc'),
    path('accept/<int:proposal_id>', views.accept_proposal, name='accept_proposal'),
    path('send/<int:proposal_id>', views.send_proposal, name='send_proposal'),
    path('send_to_me/<int:proposal_id>', views.send_proposal_to_me, name='send_proposal_to_me'),
    path('preview/', RedirectView.as_view(url='/openProposals')),
    path('preview/<int:proposal_id>/', views.proposal_preview),
    path('addNetworkDevice/<int:proposal_id>/', model_update.create_proposal_network_device),
    path('addTCODevice/<int:proposal_id>/', model_update.create_proposal_tco_device),
    path('removeNetworkDevice/<int:proposal_id>/', model_update.remove_proposal_network_device),
    path('removeTCODevice/<int:proposal_id>/', model_update.remove_proposal_tco_device),
    path('TCODeviceDetails/<int:proposal_id>/', views.tco_device_details),
    path('saveBlendedProposalData/<int:proposal_id>/', model_update.save_blended_proposal_data),
    path('saveTieredProposalData/<int:proposal_id>/', model_update.save_tiered_proposal_data),
    path('saveMarginAlert/<int:proposal_id>/', model_update.save_margin_alert),
    path('pricing/<int:proposal_id>/update_tier/', model_update.update_proposal_item_tier),
    path('updateProposalServiceItem/', model_update.update_proposal_service_item),
    path('requestStreetFighterPricing/', views.request_street_fighter_pricing),
    path('acceptStreetFighterPricing/', views.accept_street_fighter_pricing),
    path('getManagementAssumptions/', views.get_management_assumptions),
    # csv export 
    # path('consolidate-specifications/', views.consolidate_model_specifications),
    # path('build-specs/',views.build_model_specifications)
]

CONTRACT_URLS = [
    path('view/<int:proposal_id>/', views.view_contract, name='view_contract'),
]

urlpatterns = [
    #login
    path('accounts/', include('django.contrib.auth.urls')),
    ###
    path('imports/', views.import_home),
    path('', views.repDashboard),
    path('imports/parse-printer-data/', imports.import_printers),
    path('imports/import-makes/', imports.import_makes),
    path('imports/import-printer-costs/', imports.import_printer_costs),
    path('imports/import-accessories/', imports.import_accessories),
    path('imports/import-products/', imports.import_products),
    path('imports/import-toner-data/', imports.import_toners),
    path('imports/import-drums/', imports.import_drums),
    path('imports/import-developers/', imports.import_developers),
    path('imports/import-service/', imports.import_service),
    path('imports/import-device-makeup/', imports.import_device_makeup),
    path('imports/import-dca-post/<int:proposal_id>', imports.import_dca_post),
    path('imports/create-new-company/', model_update.create_company),
    path('imports/import-hw-data/', imports.import_hw_data),
    path('imports/import-supplies-data/', imports.import_supplies_data),
    path('summary/', views.summary_page),
    path('alerts/', views.alerts),
    path('alerts/getStreetFighterItems/<int:alert_id>/', views.get_street_fighter_items),
    path('alerts/saveStreetFighterCosts/<int:alert_id>/', views.save_street_fighter_costs),
    path('alerts/acceptStreetFighterPricing/<int:proposal_id>/', views.accept_street_fighter_pricing),
    path('alerts/declineStreetFighterPricing/<int:proposal_id>/', views.decline_street_fighter_pricing),

    #reps
    path('repDashboard/', views.repDashboard),
    path('proposal/', include(PROPOSAL_URLS)),
    path('contract/', include(CONTRACT_URLS)),
    path('openProposals/', views.openProposals),
    path('sentProposals/', views.sentProposals),
    path('contracts/', views.contracts),
    path('SalesRep/', views.SalesRep),
    path('settings/', views.account_settings, name='account_settings'),
    path('openProposals/proposals/', views.openProposalTableInfo),
    #anything that wants to delete a proposal can use this path below
    re_path(r'\w*/removeProposal/', model_update.delete_proposal),

    #manager
    path('manageReps/', views.manageReps),
    path('manageAssumptions/', views.manageAssumptions),
    path('manageAssumptions/update', model_update.update_assumption),
    path('manageReps/update', model_update.update_rep),
    path('manageReps/delete', model_update.delete_rep),

    #punchout  (gel 04/24/2020)
    path('punchout/', views.punchout),
    path('punchout/createNewProposal/', model_update.punchout_create_proposal),
    path('punchout/saveNewClient/', model_update.punchout_create_client),
    path('punchout/selectClient/<int:proposal_id>/', views.punchout_select_client),

    #my account
    path('myAccount/', views.my_account_equipment),
    path('myAccount/equipment/', views.my_account_equipment),
    path('myAccount/supplies/', views.my_account_supplies),
    path('myAccount/service/', views.my_account_service),
    path('myAccount/tcv/', views.my_account_tcv),
    path('myAccount/tcv/<int:proposal_id>', views.view_tcv, name="view_tcv"),
    path('myAccount/tcv/<int:proposal_id>/download', views.download_tcv, name="download_tcv"),

    # API
    path('api/', include('api.urls')),
    # leasing
    path('leasing-data/', model_update.get_leasing_data),
    path('calculate-lease-payment/', model_update.calculate_lease_payment),

    #dca import
    path('dca/accounts/<int:proposal_id>', dca.accounts),
    path('dca/device-info/<int:account_id>', dca.device_info),
    path('dca/device-data/<int:account_id>', dca.device_data),

    # print_fleet
    path('print_fleet/groups/<int:proposal_id>', print_fleet_.groups),
    path('print_fleet/group/<str:group_id>', print_fleet_.group),
    path('print_fleet/devices/<str:group_id>', print_fleet_.devices),
    path('print_fleet/device_data/<str:group_id>', print_fleet_.device_data),

    # Self-Service Portal
    path('self-service/<str:client_self_service_key>/', get_self_service_landing),
    path('self-service/<str:client_self_service_key>/<str:proposal_id>/equipment', get_self_service_equipment),
    path('self-service/<str:client_self_service_key>/<str:proposal_id>/selection', get_self_service_selection),
    path('self-service/<str:client_self_service_key>/<str:proposal_id>/review', get_self_service_review),

    path('self-service/<str:client_self_service_key>/self-service-selection', get_self_service_selection_landing),
]

simplemps/simplemps/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

#change the mps to import for stuff
urlpatterns = [
    path('', include('mps.urls')),
    path('admin/', admin.site.urls),
    # (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.IMAGE_URL})
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemps/mps/controllers/dca.py
import zeep
import json
import requests

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.core.serializers.json import DjangoJSONEncoder
from datetime import datetime, timedelta
from collections import defaultdict
from workdays import networkdays

from .import_service_items import import_service_items
from ..models import (
    Company,
    Proposal
)

@login_required
def accounts(request, proposal_id):
  proposal = Proposal.objects.get(id=proposal_id)
  company = Company.objects.get(id=proposal.sales_rep.company_id)

  if not all([company.dca_username, company.dca_password, company.dca_company, company.dca_url]):
    message = "FMAudit information has not been provided. Unable to authenticate."
    return JsonResponse(json.dumps(message), status=401, safe=False)

  url = company.dca_url
  history = zeep.plugins.HistoryPlugin()

  try:
    client = zeep.Client(wsdl=url, plugins=[history])
    client.service.Authenticate(company.dca_username, company.dca_password)
    request.session['dca_cookie'] = history.last_received['http_headers']['Set-Cookie']
    request.session['dca_url'] = url
    request.session['ticket'] = client.service.GetAuthTicket(company.dca_username, company.dca_password)
  except:
    message = "Unable to authenticate with FMAudit."
    return JsonResponse(json.dumps(message), status=401, safe=False)

  request.session['proposal_id'] = proposal_id

  accounts_request = client.service.GetAccountsInfo(company.dca_company)

  accounts_info = zeep.helpers.serialize_object(accounts_request)

  accounts_info_sorted = sorted(accounts_info["Accounts"]["FMAAccount"], key=lambda k: k['Name'])

  return JsonResponse(json.dumps(accounts_info_sorted), safe=False)

@login_required
def device_info(request, account_id):
  url = request.session['dca_url']
  history = zeep.plugins.HistoryPlugin()
  client = zeep.Client(wsdl=url, plugins=[history])
  cookie = request.session['dca_cookie']

  client.transport.session.headers.update({'Cookie': cookie})

  devices_response = client.service.GetDevicesForAccount(account_id)

  device_info = zeep.helpers.serialize_object(devices_response)

  unique_models = {}

  if device_info['Devices']:
    for device in device_info['Devices']['FMADevice']:
      if device.get('Model') and device.get('Manufacturer') and device.get('DeviceID'):
        if device['Model'] not in unique_models:
          unique_models[device["Manufacturer"] + " " + device['Model']] = [device["DeviceID"]]
        else:
          [device["Manufacturer"] + " " + device["Model"]].append(device["DeviceID"])

  request.session['dca_device_info'] = unique_models

  return JsonResponse(json.dumps(unique_models, cls=DjangoJSONEncoder), safe=False)

@login_required
def device_data(request, account_id):
  url = request.session['dca_url']
  history = zeep.plugins.HistoryPlugin()
  client = zeep.Client(wsdl=url, plugins=[history])
  cookie = request.session['dca_cookie']
  client.transport.session.headers.update({'Cookie': cookie})

  start_date = datetime.today() - timedelta(days=60)
  end_date = datetime.today()

  unique_models = request.session['dca_device_info']
  proposal_id = request.session['proposal_id']
  meter_response = client.service.GetAllMetersDataForAccountID(request.session['ticket'], account_id, start_date, end_date)
  device_data = zeep.helpers.serialize_object(meter_response)

  # read in DCA items, group all similar items
  dca_items = defaultdict(lambda: defaultdict(lambda: 0))

  if (device_data['Devices'] and device_data['Devices']['Device']):
    for device in device_data['Devices']['Device']:
      if (device["Meters"] and device["Meters"]["Meter"]):
        device_model = device.get("Manufacturer", "") + " " + device.get("Model", "")

        if device_model in unique_models:
          amv_calculations = calculateAMV(device["Meters"]["Meter"])

          if amv_calculations != "Invalid":
            device_name = (device["Manufacturer"] + " " + device['Model']).lower()
            dca_items[device_name]['count'] += 1
            dca_items[device_name]['Mono AMV'] += amv_calculations["mono_amv"]
            dca_items[device_name]['Color AMV'] += amv_calculations["color_amv"]

  count = import_service_items(proposal_id, dca_items)

  if (count == 0):
    message = "Unable to import. There have been no meter reads for the selected account in the last 60 days."
    return JsonResponse(json.dumps(message), safe=False)

  message = "Successfully imported {} items!".format(count)

  return JsonResponse(json.dumps(message), safe=False)

def calculateAMV(meter):
  start_date = None
  end_date = None

  start_mono_count = 0
  end_mono_count = 0
  start_color_count = None
  end_color_count = None

  for reading in meter:
    date = reading["Date"]
    if start_date == None or date <= start_date:
      start_date = date

      if reading["Name"] == "MonoPages":
        start_mono_count = reading["Reading"]

      if reading["Name"] == "ColorPages":
        start_color_count = reading["Reading"]

    if end_date == None or date >= end_date:
      end_date = date

      if reading["Name"] == "MonoPages":
        end_mono_count = reading["Reading"]

      if reading["Name"] == "ColorPages":
        end_color_count = reading["Reading"]

  if (len(meter) == 0 or end_date == start_date):
    return "Invalid"

  date_diff = end_date - start_date

  mono_count = (end_mono_count - start_mono_count) / networkdays(start_date, end_date)

  # TODO: fix the edit page, it breaks if this is 0
  mono_count = 5 if mono_count == 0 else mono_count

  color_count = 0
  if start_color_count is not None and end_color_count is not None:
    color_count = (end_color_count - start_color_count) / networkdays(start_date, end_date)
    color_count = 5 if color_count == 0 else color_count

  amv_calculations = { "color_amv": round(color_count), "mono_amv": round(mono_count) }

  return amv_calculations

simplemps/mps/templates/rep/SalesRep.html
{% extends 'baseTemplate.html' %}
{% load static from staticfiles %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'css/manager/manageReps.css' %}">
<link rel="stylesheet" href="{% static 'css/rep/openProposals.css' %}">
<link rel="stylesheet" href="{% static 'csslib/DataTables/datatables.min.css' %}">
{% endblock %}

{% block page_js %}
<script type="text/javascript" language="javascript" src="{% static 'js/csrfSetUp.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/rep/openProposals.js' %}"></script>
<script src="{% static 'jslib/DataTables/datatables.min.js'%}"></script>

{% endblock %}

{% block page_content %}
{% csrf_token %}
<div class="grid-x">
    <div class="cell large-23 align-middle">
        <div class="text-center callout border-none title">
            <h6>Open Proposals</h6>
        </div>
    </div>
    <div class='grid-x large-23'>
        <div class="cell">
            <div id="table-body">
                <table id="open-proposals">
                    <thead style="background-color: var(--mps-yellow);">
                        <td>Proposal ID</td>
                        <td>Company</td>
                        <td>Sales Rep</td>
                        <td>Date Edited</td>
                        <td>Status</td>
                        <td>Actions</td>
                    </thead>
                    <tbody style="background-color: var(--mps-blue);">
                        {% if dashboard_prop_prog %}
                            {% for entry in dashboard_prop_prog%}
                                <tr>
                                    <td>{{entry.proposal_id}}</td>
                                    <td>{{entry.client}}</td>
                                    <td>{{ entry.sales_rep_name}}</td>
                                    <td>{{entry.date_edited}}</td>
                                    <td>{{entry.status}}</td>
                                    <td>
                                        <button class="edit" id="e{{entry.proposal_id}}">
                                            <i class="fas fa-edit"></i>
                                        </button>
                                        <button class="delete" id="d{{entry.proposal_id}}">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </td>
                                </tr>

                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="6" class="text-center">you have no open proposals</td>
                            </tr>
                        {% endif %}
                    </tbody>
                    <tfoot>
                        <td colspan="6" class="text-center">
                            <button id="add-proposal"><i class="fas fa-plus-circle"></i></button>
                        </td>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <div class="grid-x large-23 hide">
        <button class="cell large-3 large-offset-21 button proposal-button">New Proposal</button>
    </div>
</div>
{% endblock %}

simplemps/mps/templates/rep/account_settings.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Settings</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if image_url is None and co_branding_logo_url is None %}
          <button type="submit">Upload Logo</button>
        {% endif %}
    </form>

    {% if image_url or co_branding_logo_url %}
      <h2>Successfully uploaded!</h2>
    {% endif %}

    {% if image_url %}
        <h3>Logo:</h3>
        <p><img src="{{ image_url }}"/></p>
    {% endif %}

    {% if co_branding_logo_url %}
        <h3>Co-branding Logo:</h3>
        <p><img src="{{ co_branding_logo_url }}"/></p>
    {% endif %}
    
    <p><a href="/">Return to Dashboard</a></p>

</body>
</html>

simplemps/mps/templates/rep/alerts.html
{% extends 'baseTemplate.html' %}
{% load static from staticfiles %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'css/manager/alerts.css' %}">
<link rel="stylesheet" href="{% static 'csslib/DataTables/datatables.min.css' %}">
{% endblock %}

{% block page_js %}
<script src="{% static 'jslib/DataTables/datatables.min.js'%}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/csrfSetUp.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/manager/manageAlerts.js' %}"></script>
{% endblock %}

{% block page_content %}
{% csrf_token %}
<div class="grid-x ma-content">
    <div class="cell large-15">
        <div class="text-center callout title">
            <h6>Proposal Margin Alerts</h6>
        </div>
    </div>
    <div class="cell large-15">
        <table id="marginAlerts" class="mps-table">
            <thead>
                <tr>
                    <th>Alert Date</th>
                    <th>Proposal</th>
                    <th>Representative</th>
                    <th>Client</th>
                    <th>Number of Devices</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for alert in margin_alerts %}
                    <tr id="alert-{{ alert.id }}">
                        <td>{{ alert.create_date }}</td>
                        <td>{{ alert.proposal_id }}</td>
                        <td>{{ alert.rep }}</td>
                        <td>{{ alert.client }}</td>
                        <td>{{ alert.num_devices }}</td>
                        <td>
                            <a href="{% url 'mps:proposal_pricing' alert.proposal_id %}"><i class="fas fa-search size-18"></i></a>
                            <button onclick="approveMarginAlert({{ alert.id }}, {{ request.user.mps_user.id }})"><i class="fas fa-check size-18"></i></button>
                            <button onclick="denyMarginAlert({{ alert.id }}, {{ request.user.mps_user.id }})"><i class="fas fa-times size-18"></i></button>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6" class="text-center">There are no Margin Alerts</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="grid-x sf-content">
    <div class="cell large-15">
        <div class="text-center callout title">
            <h6>Street Fighter Requests</h6>
        </div>
    </div>
    <div class="cell large-15">
        <table id="sfRequests" class="mps-table">
            <thead>
                <tr>
                    <th>Request Date</th>
                    <th>Proposal</th>
                    <th>Representative</th>
                    <th>Client</th>
                    <th>Number of Devices</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for alert in sf_alerts %}
                    <tr id="alert-{{ alert.id }}">
                        <td>{{ alert.create_date }}</td>
                        <td>{{ alert.proposal_id }}</td>
                        <td>{{ alert.rep }}</td>
                        <td>{{ alert.client }}</td>
                        <td>{{ alert.num_devices }}</td>
                        <td>
                            <button onclick="openStreetFighterReq( {{ alert.id }} )"><i class="fas fa-search size-18"></i></button>
                            <button><i class="fas fa-check size-18"></i></button>
                            <button><i class="fas fa-times size-18"></i></button>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6" class="text-center">There are no Steet Fighter requests</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="full reveal" id="streetFighterReveal" data-reveal data-overlay="true">
        <div class="grid-x grid-padding-y align-middle modal-header mps-blue">
            <div class="cell large-21 large-offset-1">
                <h6 class="bold">Street Fighter Items</h6>
            </div>
            <div class="cell large-1 text-center">
                <button data-close aria-label="Close reveal" type="button">
                    <h6>X</h6>
                </button>
            </div>
        </div>
        <div id="sfRevealBody"></div>
    </div>
</div>
{% endblock %}

simplemps/mps/templates/rep/contracts.html
{% extends 'baseTemplate.html' %}
{% load static from staticfiles %}

{% block page_css %}
<link rel="stylesheet" href="{% static 'css/manager/manageReps.css' %}">
<link rel="stylesheet" href="{% static 'css/rep/openProposals.css' %}">
<link rel="stylesheet" href="{% static 'csslib/DataTables/datatables.min.css' %}">
{% endblock %}

{% block page_js %}
<script type="text/javascript" language="javascript" src="{% static 'js/csrfSetUp.js' %}"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/rep/proposal/contract.js' %}"></script>
<script src="{% static 'jslib/DataTables/datatables.min.js'%}"></script>

{% endblock %}

{% block page_content %}
{% csrf_token %}
<div class="grid-x">
    <div class="cell large-23 align-middle">
        <div class="text-center callout border-none title">
            <h6>Open Contracts</h6>
        </div>
    </div>
    <div class='grid-x large-23'>
        <div class="cell">
            <div id="table-body">
                <table id="open-proposals">
                    <thead style="background-color: var(--mps-yellow);">
                        <td>Proposal ID</td>
                        <td>Company</td>
                        <td>Date Edited</td>
                        <td>Status</td>
                        <td>Actions</td>
                    </thead>
                    <tbody style="background-color: var(--mps-blue);">
                        {% if dashboard_prop_prog %}
                            {% for entry in dashboard_prop_prog%}
                                <tr>
                                    <td>{{entry.proposal_id}}</td>
                                    <td>{{entry.client}}</td>
                                    <td>{{entry.date_edited}}</td>
                                    <td>{{entry.status}}</td>
                                    <td>
                                        <button class="edit" id="e{{entry.proposal_id}}">
                                            <i class="fas fa-edit"></i>
                                        </button>
                                        <button class="delete" id="d{{entry.proposal_id}}">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="6" class="text-center">You have no accepted proposals.</td>
                            </tr>
                        {% endif %}
                    </tbody>

                </table>
            </div>
        </div>
    </div>
    <div class="grid-x large-23 hide">
        <button class="cell large-3 large-offset-21 button proposal-button">New Proposal</button>
    </div>
</div>
{% endblock %}

simplemps/mps/templates/rep/repSidebar.html
{% load template_group %}

<ul class="vertical menu cell">
    <li id="dash"><a href="/repDashboard">Dashboard</a></li>
    <li id="open"><a href="/openProposals">Open Proposals</a></li>
    <li id="sent"><a href="/sentProposals">Sent Proposals</a></li>
    <li id="contracts"><a href="/contracts">Contracts</a></li>
    {% if self_service_key %}
        <li class=""><a href="/self-service/{{self_service_key}}/">Self Service Portal</a></li>
    {% endif %}
    {% if request.user|has_group:'Admin' or request.user|has_group:'Manager' %}
        <li id="sales_rep"><a href="/SalesRep">Sales Rep</a></li>
    {% endif %}
    {% if request.user|has_group:'Admin' %}
        <li id="reps"><a href="/manageReps">Sales Representatives</a></li>
    {% endif %}
    {% if request.user|has_group:'Admin' or request.user|has_group:'Manager' %}
        <li id="assmpts"><a href="/manageAssumptions">Management Assumptions</a></li>
    {% endif %}
    {% if request.user|has_group:'Admin' or request.user|has_group:'Manager' %}
        <li id="alerts"><a href="/alerts">Proposal Alerts</a></li>
    {% endif %}
    {% if request.user|has_group:'Admin' or request.user|has_group:'Manager' %}
        <li><a href="/myAccount">My Account</a></li>
    {% endif %}
    {% if request.user|has_group:'Admin' or request.user|has_group:'Manager' %}
        <li><a href="/settings">Settings</a></li>
    {% endif %}
    {% if request.user|has_group:'Admin' %}
        <li><a href="/imports">Imports</a></li>
    {% endif %}
        <li><a href="{% url 'mps:logout' %}">Logout</a></li>
</ul>